name: Check & Fix Styling

on: [pull_request]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Check & Fix Styling
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php-cs-fixer.php --allow-risky=yes

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4.15.4
        with:
          commit_message: Check & Fix Styling
