name: Fix PHP Code Style

on: [pull_request]

jobs:
  php-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Fix PHP Code Style
        uses: aglipanci/laravel-pint-action@v2

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Fix PHP Code Style
