name: Laravel Pint
'on':
  - pull_request
jobs:
  php-code-styling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: '${{ github.head_ref }}'
      - name: Laravel Pint
        uses: aglipanci/laravel-pint-action@2.1.0
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Laravel Pint
