name: Laravel Pint

on: [pull_request]

jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: "laravel-pint"
          uses: aglipanci/laravel-pint-action@2.1.0
          with:
            preset: laravel
            verboseMode: true
            testMode: true
            configPath: "vendor/my-company/coding-style/pint.json"
            pintVersion: 1.6.0
